"use client";
import { useState } from "react";
import { CartesianGrid, Line, LineChart, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { latestMorningMeetingMonth, morningMeetingMonths, productionKpiActualRows, type ProductionKpiActualRow } from "@/data/morningMeetingActualData";
import ActionPlanPanel from "@/features/morning-meeting/ActionPlanPanel";
import KpiStatusCard from "@/features/morning-meeting/KpiStatusCard";
import { formatKpiValue, formatTarget, statusForValue } from "@/features/morning-meeting/morningMeetingUtils";

export default function ProductionKpiPage() {
  const [selected, setSelected] = useState<ProductionKpiActualRow>(productionKpiActualRows[0]);
  const chartData = morningMeetingMonths.map((month) => ({ month: month.replace("2026-", ""), value: selected.monthly[month], t1: selected.target.t1, t2: selected.target.t2 }));
  const latestValue = selected.monthly[latestMorningMeetingMonth];
  const latestStatus = statusForValue(selected, latestValue);

  return <div className="mm-page"><section className="mm-hero compact"><div><span>Production KPI</span><h1>17 KPI Jan-Jul 2026</h1><p>Nilai aktual berasal dari source JSON dan warna dihitung otomatis dengan aturan T1/T2.</p></div><KpiStatusCard title={selected.kpi.nama} meta={`${selected.kpi.dimensi} · ${selected.pic ?? selected.kpi.picUtama}`} value={formatKpiValue(selected.kpi, latestValue)} target={`T1 ${formatTarget(selected.kpi, selected.target.t1)} · T2 ${formatTarget(selected.kpi, selected.target.t2)}`} status={latestStatus} reason={`Juli 2026: ${formatKpiValue(selected.kpi, latestValue)}`} /></section><div className="mm-kpi-layout"><section className="mm-panel"><h2>Master KPI dan Aktual Bulanan</h2><div className="mm-table-wrap"><table className="mm-table"><thead><tr><th>KPI</th><th>Bobot</th><th>PIC</th><th>T1</th><th>T2</th>{morningMeetingMonths.map((month) => <th key={month}>{month.replace("2026-", "")}</th>)}</tr></thead><tbody>{productionKpiActualRows.map((row) => <tr key={row.kpi.id} className={selected.kpi.id === row.kpi.id ? "selected" : ""} onClick={() => setSelected(row)}><td><b>{row.kpi.nama}</b><span>{row.kpi.dimensi}</span></td><td>{row.kpi.bobot ?? "-"}</td><td>{row.pic ?? row.kpi.picUtama}</td><td>{formatTarget(row.kpi, row.target.t1)}</td><td>{formatTarget(row.kpi, row.target.t2)}</td>{morningMeetingMonths.map((month) => { const value = row.monthly[month]; return <td key={month}><span className={`mm-cell ${statusForValue(row, value)}`}>{formatKpiValue(row.kpi, value)}</span></td>; })}</tr>)}</tbody></table></div></section><aside className="mm-panel mm-chart-panel"><h2>Tren {selected.kpi.nama}</h2><ResponsiveContainer width="100%" height={280}><LineChart data={chartData} margin={{ top: 12, right: 20, bottom: 8, left: 0 }}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="month" /><YAxis /><Tooltip /><ReferenceLine y={selected.target.t1} stroke="#ef4444" strokeDasharray="4 4" label="T1" /><ReferenceLine y={selected.target.t2} stroke="#22c55e" strokeDasharray="4 4" label="T2" /><Line type="monotone" dataKey="value" stroke="#2563eb" strokeWidth={3} dot={{ r: 4 }} connectNulls={false} /></LineChart></ResponsiveContainer><div className="mm-detail-list"><span>Arah: {selected.kpi.arah === "turun" ? "lebih kecil lebih baik" : "lebih besar lebih baik"}</span><span>Aktual 2026 Excel: {formatKpiValue(selected.kpi, selected.aktual2026Excel)}</span><span>Frekuensi: {selected.kpi.frekuensi}</span></div><ActionPlanPanel row={selected} /></aside></div></div>;
}
